### ISSUE TITLE
Error when debugging: couldn't find "libDmSDKJni.so" 

### ISSUE THREAD

**Issue by nmz787** [lnanek/AutoChatSticker#1]
I git cloned the repo, then opened this in Android-Studio... it had to download some SDK stuff, I then started the debugger, but I get this in the output log almost immediately.

```
08-25 23:16:45.930 2627-2627/com.htc.sample.duallens I/art: Late-enabling -Xcheck:jni
08-25 23:16:45.931 2627-2627/com.htc.sample.duallens I/art: VMHOOK: rlim_cur : 0 pid:2627
08-25 23:16:46.127 2627-2627/com.htc.sample.duallens W/System: ClassLoader referenced unknown path: /data/app/com.htc.sample.duallens-2/lib/arm
08-25 23:16:46.670 2627-2627/com.htc.sample.duallens I/art: override thread count:-j2
08-25 23:16:47.386 2627-2627/com.htc.sample.duallens W/System: ClassLoader referenced unknown path: /data/app/com.htc.sample.duallens-2/lib/arm
08-25 23:16:47.822 2627-2627/com.htc.sample.duallens D/DualLensActivity: originalImageBitmap width = 2688
08-25 23:16:47.822 2627-2627/com.htc.sample.duallens D/DualLensActivity: originalImageBitmap height = 1520
08-25 23:16:54.004 2627-2627/com.htc.sample.duallens W/SystemReader: Cannot find htc_album_feature_diff, use default value instead
08-25 23:16:54.005 2627-2627/com.htc.sample.duallens I/DepthMapSDK: Load Jni (dmSDK_jni) Shared lib! Supported?true
08-25 23:16:54.011 2627-2627/com.htc.sample.duallens W/System.err: java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.htc.sample.duallens/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.htc.sample.duallens/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.htc.sample.duallens/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.htc.sample.duallens/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.htc.sample.duallens/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.htc.sample.duallens/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.htc.sample.duallens/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.htc.sample.duallens/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.htc.sample.duallens/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.htc.sample.duallens/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.htc.sample.duallens/files/instant-run/dex/slice-htcduallens_a87c1dde5cbafd0f472f6e9412e6344fae5c35b4-classes.dex", dex file "/data/data/com.htc.sample.duallens/files/instant-run/dex/slice-htccustomization_39d605f531b6064339c27cdfe84c8d6fd11a12be-classes.dex", dex file "/data/data/com.htc.sample.duallens/files/instant-run/dex/slice-commons-io-2.4_cf564d0fa362b074491063288dbc9c2d0baae401-classes.dex"],nativeLibraryDirectories=[/data/app/com.htc.sample.duallens-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libDmSDKJni.so"
08-25 23:16:54.011 2627-2627/com.htc.sample.duallens W/System.err:     at java.lang.Runtime.loadLibrary(Runtime.java:367)
08-25 23:16:54.011 2627-2627/com.htc.sample.duallens W/System.err:     at java.lang.System.loadLibrary(System.java:1076)
08-25 23:16:54.011 2627-2627/com.htc.sample.duallens W/System.err:     at com.htc.lib1.duallens.DualLens.<clinit>(DualLens.java:326)
08-25 23:16:54.011 2627-2627/com.htc.sample.duallens W/System.err:     at com.htc.sample.duallens.DualLensActivity.onResume(DualLensActivity.java:140)
08-25 23:16:54.011 2627-2627/com.htc.sample.duallens W/System.err:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1326)
08-25 23:16:54.011 2627-2627/com.htc.sample.duallens W/System.err:     at android.app.Activity.performResume(Activity.java:6323)
08-25 23:16:54.011 2627-2627/com.htc.sample.duallens W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3311)
08-25 23:16:54.011 2627-2627/com.htc.sample.duallens W/System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3359)
08-25 23:16:54.012 2627-2627/com.htc.sample.duallens W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2549)
08-25 23:16:54.012 2627-2627/com.htc.sample.duallens W/System.err:     at android.app.ActivityThread.access$900(ActivityThread.java:150)
08-25 23:16:54.012 2627-2627/com.htc.sample.duallens W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394)
08-25 23:16:54.012 2627-2627/com.htc.sample.duallens W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
08-25 23:16:54.012 2627-2627/com.htc.sample.duallens W/System.err:     at android.os.Looper.loop(Looper.java:168)
08-25 23:16:54.012 2627-2627/com.htc.sample.duallens W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5845)
08-25 23:16:54.012 2627-2627/com.htc.sample.duallens W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-25 23:16:54.012 2627-2627/com.htc.sample.duallens W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
08-25 23:16:54.012 2627-2627/com.htc.sample.duallens W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
08-25 23:16:54.013 2627-2627/com.htc.sample.duallens W/System.err: java.io.IOException
08-25 23:16:54.013 2627-2627/com.htc.sample.duallens W/System.err:     at com.htc.lib1.duallens.DualLens.prepare(DualLens.java:135)
08-25 23:16:54.013 2627-2627/com.htc.sample.duallens W/System.err:     at com.htc.sample.duallens.DualLensActivity.onResume(DualLensActivity.java:166)
08-25 23:16:54.013 2627-2627/com.htc.sample.duallens W/System.err:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1326)
08-25 23:16:54.013 2627-2627/com.htc.sample.duallens W/System.err:     at android.app.Activity.performResume(Activity.java:6323)
08-25 23:16:54.013 2627-2627/com.htc.sample.duallens W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3311)
08-25 23:16:54.013 2627-2627/com.htc.sample.duallens W/System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3359)
08-25 23:16:54.013 2627-2627/com.htc.sample.duallens W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2549)
08-25 23:16:54.014 2627-2627/com.htc.sample.duallens W/System.err:     at android.app.ActivityThread.access$900(ActivityThread.java:150)
08-25 23:16:54.014 2627-2627/com.htc.sample.duallens W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394)
08-25 23:16:54.014 2627-2627/com.htc.sample.duallens W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
08-25 23:16:54.014 2627-2627/com.htc.sample.duallens W/System.err:     at android.os.Looper.loop(Looper.java:168)
08-25 23:16:54.014 2627-2627/com.htc.sample.duallens W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5845)
08-25 23:16:54.014 2627-2627/com.htc.sample.duallens W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-25 23:16:54.014 2627-2627/com.htc.sample.duallens W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
08-25 23:16:54.014 2627-2627/com.htc.sample.duallens W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
08-25 23:16:54.110 2627-2954/com.htc.sample.duallens I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3__release_AU (I3fa967cfef)
                                                                   OpenGL ES Shader Compiler Version: E031.28.00.02
                                                                   Build Date: 09/29/15 Tue
                                                                   Local Branch: mybranch14683032
                                                                   Remote Branch: quic/master
                                                                   Local Patches: NONE
                                                                   Reconstruct Branch: NOTHING
```

**Comment by lnanek** [comment]
You need the Dual Lens SDK, most likely:
https://www.htcdev.com/devcenter/opensense-sdk/htc-dual-lens-api

**Comment by lnanek** [comment]
You are running the program on the HTC One (M8), right? That's also
required.

**Comment by nmz787** [comment]
Yes I have two One M8 phones. When debugging I found mention of needing to
move the .so files to a jniLibs dir, but after recompiling I get a
different .so missing error instead. I have the Dual Lens SDK, but it
doesn't seem to have the .so file the debugger complains about. It seems
this Android build system isn't backwards compatible, so I'm guessing there
are some simple magic values and special file locations or config files to
update.

**Comment by lnanek** [comment]
Hmm, well you can see the first .so complained about here:
https://github.com/lnanek/AutoChatSticker/tree/master/libs/armeabi-v7a

So maybe in a modern Android Studio build you'd have to add
a jniLibs.srcDir source directory entry with that location to the
build.gradle.

Thank you, Lance Nanek / programmer
646-409-2810

**Comment by nmz787** [comment]
Any chance you could get this updated to work with the latest Android Studio? I am getting no where except having a big bad headache :(   This seems to happen each time I want to do something with Android development... thought I will admit my ideas always seem to be outside the normal flow for most Android apps (wanting to use this manufacturer-specific C/C++-based SDK) (wanting to use the non-free modules of openCV which require compiling the C++). Everytime I try to get into this, I just get a headache and waste days of time, just to give up and come back years later and find none of my previous ramping-up means anything because Android has changed everything it seems.

**Comment by lnanek** [comment]
I wouldn't mind, but don't have an M8. I can email someone who still works at HTC and see if they have bandwidth to update, I guess.

**Comment by lnanek** [comment]
You can try this commit:  
https://github.com/lnanek/AutoChatSticker/commit/3d24604e3a021e174e7934e641bc826a961731a3#diff-c197962302397baf3a4cc36463dce5eaR33

When I run this after applying it:  
./gradlew assembleDebug

The resulting APK does have the .so files included:

```
➜  AutoChatSticker git:(master) unzip -l build/apk/AutoChatSticker-debug-unaligned.apk
Archive:  build/apk/AutoChatSticker-debug-unaligned.apk
  Length     Date   Time    Name
 --------    ----   ----    ----
  1536054  09-07-16 14:58   assets/coloridx.bmp
  1536054  09-07-16 14:58   assets/coloridx_old.bmp
  2482215  09-07-16 14:57   assets/dualLensSample.jpg
     1576  09-07-16 14:58   res/layout/activity_main.xml
     2148  09-07-16 14:58   AndroidManifest.xml
     2204  09-07-16 14:57   resources.arsc
     5964  09-07-16 14:57   res/drawable-hdpi/ic_launcher.png
     3112  09-07-16 14:57   res/drawable-mdpi/ic_launcher.png
     9355  09-07-16 14:57   res/drawable-xhdpi/ic_launcher.png
    17889  09-07-16 14:57   res/drawable-xxhdpi/ic_launcher.png
   488676  09-07-16 14:58   classes.dex
    11562  09-07-16 14:58   META-INF/LICENSE.txt
      178  09-07-16 14:58   META-INF/NOTICE.txt
    62992  09-07-16 14:52   lib/armeabi-v7a/libDmSDKJni.so
   608848  09-07-16 14:52   lib/armeabi-v7a/libHMSGallery_libDualLens.so
  2126440  09-07-16 14:52   lib/armeabi-v7a/libHMSGallery_libSegBokeh.so
     1355  09-07-16 14:58   META-INF/MANIFEST.MF
     1384  09-07-16 14:58   META-INF/CERT.SF
      920  09-07-16 14:58   META-INF/CERT.DSA
```

**Comment by nmz787** [comment]
Thanks! That was a lot smoother to get going than previously. Now on to another issue :/ :)
